version: '3.8'

services:
  database:
    container_name: database
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '3306:3306'
    volumes:
      - ${WEBAPP_STORAGE_HOME}/mysql:/var/lib/mysql
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    environment:
      PMA_PORT: 3306
      PMA_HOST: database
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - 8081:80
    depends_on:
      - database
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ${WEBAPP_STORAGE_HOME}/app:/var/www/symfony_docker
    depends_on:
      - database
      - pma
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ${WEBAPP_STORAGE_HOME}/app:/var/www/symfony_docker
      - ${WEBAPP_STORAGE_HOME}/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
